# Generated by Django 2.2 on 2019-04-18 18:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_auto_20190418_1417'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatroom',
            name='start_time',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
